### ISSUE TITLE
The code for visualization

### ISSUE THREAD

**Issue by shanice-l** [rasmushaugaard/surfemb#10]
Hi, authors!

Thank you for your great work! The visualization results in your paper and website are amazing, so would you please offer us the visualization code additionally?

**Comment by rasmushaugaard** [comment]
Hi there

Thank you!
With infer_debug.py you can [inspect](https://github.com/rasmushaugaard/surfemb#inference-inspection) the learnt queries, keys and distributions, much like on the project site.
The web code is available [here](https://github.com/surfemb/surfemb.github.io/tree/main/src).
