### ISSUE TITLE
Then remove invisible parts of the objects

### ISSUE THREAD

**Issue by cats0212** [rasmushaugaard/surfemb#11]
I run `python -m surfemb.scripts.misc.surface_samples_remesh_visible`
AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'repair_non_manifold_edges_by_removing_faces'

I install pymeshlab==0.2.1 to fix it.
But it cause another problem:

  0%|          | 0/21 [00:00<?, ?it/s]
/home/c/surfemb/data/bop/ycbv/models/obj_000013.ply

----------AngleRad 0.523599 Angledeg 30.000000 ratio 0.066987 vn 256 vn2 3821 
asked 3821 got 3821 (expecting 255 instead of 256)
  0%|          | 0/21 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/c/surfemb/surfemb/scripts/misc/surface_samples_remesh_visible.py", line 42, in <module>
    area_reduction = trimesh.load_mesh(remesh_fp).area / trimesh.load_mesh(mesh_fp).area
  File "/home/c/anaconda3/envs/surfemb/lib/python3.8/site-packages/trimesh/constants.py", line 153, in timed
    result = method(*args, **kwargs)
  File "/home/c/anaconda3/envs/surfemb/lib/python3.8/site-packages/trimesh/exchange/load.py", line 209, in load_mesh
    results = mesh_loaders[file_type](file_obj,
  File "/home/c/anaconda3/envs/surfemb/lib/python3.8/site-packages/trimesh/exchange/ply.py", line 106, in load_ply
    ply_binary(elements, file_obj)
  File "/home/c/anaconda3/envs/surfemb/lib/python3.8/site-packages/trimesh/exchange/ply.py", line 881, in ply_binary
    raise ValueError('File is unexpected length!')
ValueError: File is unexpected length!

**Comment by cp1108** [comment]
# packages in environment at /home/chenpu/anaconda3/envs/surfemb:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   1.0.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
albumentations            1.0.3              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
async-timeout             4.0.2                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
blas                      1.0                         mkl  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.3.29            h06a4308_1  
cachetools                5.0.0                    pypi_0    pypi
cairo                     1.16.0               hf32fb01_1  
certifi                   2021.10.8        py38h06a4308_2  
cffi                      1.15.0           py38hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.2                    pypi_0    pypi
cloudpickle               2.0.0              pyhd3eb1b0_0  
cryptography              36.0.0           py38h9ce1e76_0  
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.11.0             pyhd3eb1b0_0  
cytoolz                   0.11.0           py38h7b6447c_0  
dask-core                 2022.2.1           pyhd3eb1b0_0  
dbus                      1.13.18              hb2f20db_0  
docker-pycreds            0.4.0                    pypi_0    pypi
expat                     2.4.4                h295c915_0  
ffmpeg                    4.3.2                h37c90e5_3    conda-forge
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.11.0               h70c0345_0  
frozenlist                1.3.0                    pypi_0    pypi
fsspec                    2022.2.0           pyhd3eb1b0_0  
geos                      3.8.0                he6710b0_0  
gettext                   0.21.0               hf68c758_0  
giflib                    5.2.1                h7b6447c_0  
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.27                   pypi_0    pypi
glcontext                 2.3.6                    pypi_0    pypi
glib                      2.68.4               h9c3ff4c_0    conda-forge
glib-tools                2.68.4               h9c3ff4c_0    conda-forge
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.6.6                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
graphite2                 1.3.14               h23475e2_0  
grpcio                    1.44.0                   pypi_0    pypi
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.18.5               h76c114f_0    conda-forge
harfbuzz                  3.0.0                h83ec7ef_1    conda-forge
hdf5                      1.12.1               h69dfa17_1  
icu                       68.1                 h2531618_0  
idna                      3.3                pyhd3eb1b0_0  
imageio                   2.9.0              pyhd3eb1b0_0  
imgaug                    0.4.0              pyhd8ed1ab_1    conda-forge
importlib-metadata        4.11.3                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
jasper                    2.0.14               hd8c5072_2  
jbig                      2.1                  hdba287a_0  
jpeg                      9e                   h7f8727e_0  
kiwisolver                1.3.2            py38h295c915_0  
krb5                      1.19.2               hac12032_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
lerc                      3.0                  h295c915_0  
libblas                   3.9.0            12_linux64_mkl    conda-forge
libcblas                  3.9.0            12_linux64_mkl    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.82.0               h0b77cf5_0  
libdeflate                1.8                  h7f8727e_5  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0              h1d223b6_16    conda-forge
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libglib                   2.68.4               h3e27bee_0    conda-forge
libglu                    9.0.0                hf484d3e_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
liblapack                 3.9.0            12_linux64_mkl    conda-forge
liblapacke                3.9.0            12_linux64_mkl    conda-forge
libllvm11                 11.1.0               h3826bc1_1  
libnghttp2                1.46.0               hce63b2e_0  
libopencv                 4.5.3            py38h66b0e6b_5    conda-forge
libpng                    1.6.37               hbc83047_0  
libpq                     12.9                 hc2c5182_1  
libprotobuf               3.18.1               h780b84a_0    conda-forge
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              11.2.0              he4da1e4_16    conda-forge
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.3.0                h6f004c6_2    conda-forge
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.0.3                h7f8727e_2  
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.14                 h7b6447c_0  
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
llvm-openmp               13.0.1               he0ac6c6_1    conda-forge
locket                    0.2.1            py38h06a4308_2  
lz4-c                     1.9.3                h295c915_1  
markdown                  3.3.6                    pypi_0    pypi
matplotlib                3.5.1            py38h06a4308_1  
matplotlib-base           3.5.1            py38ha18d171_1  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
moderngl                  5.6.4                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
munkres                   1.1.4                      py_0  
mysql-common              8.0.27               ha770c72_3    conda-forge
mysql-libs                8.0.27               hfa10184_3    conda-forge
ncurses                   6.3                  h7f8727e_2  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.7.1              pyhd3eb1b0_0  
nspr                      4.33                 h295c915_0  
nss                       3.74                 h0370c37_0  
numpy                     1.21.5           py38he7a7128_1  
numpy-base                1.21.5           py38hf524024_1  
oauthlib                  3.2.0                    pypi_0    pypi
opencv                    4.5.3            py38h578d9bd_5    conda-forge
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1n               h7f8727e_0  
packaging                 21.3               pyhd3eb1b0_0  
partd                     1.2.0              pyhd3eb1b0_1  
pathtools                 0.1.2                    pypi_0    pypi
pcre                      8.45                 h295c915_0  
pillow                    9.0.1            py38h22f2fdc_0  
pip                       21.2.4           py38h06a4308_0  
pixman                    0.40.0               h7f8727e_1  
promise                   2.3                      pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
py-opencv                 4.5.3            py38he5a9106_5    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydeprecate               0.3.2                    pypi_0    pypi
pymeshlab                 2021.7                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.4              pyhd3eb1b0_0  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.13               h12debd9_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.11.0          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
pytorch-lightning         1.6.2                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.0.9           py38_torch_1.11.0_cu102    pyg
pywavelets                1.3.0            py38h7f8727e_0  
pyyaml                    6.0              py38h7f8727e_1  
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd3eb1b0_0  
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
rtree                     1.0.0                    pypi_0    pypi
scikit-image              0.16.2           py38h0573a6f_0  
scipy                     1.7.3            py38hc147768_0  
sentry-sdk                1.5.10                   pypi_0    pypi
setproctitle              1.2.3                    pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0  
shapely                   1.7.1            py38h1728cc4_0  
shortuuid                 1.0.8                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.38.2               hc218d9a_0  
tensorboard               2.8.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
toolz                     0.11.2             pyhd3eb1b0_0  
torchmetrics              0.8.1                    pypi_0    pypi
torchvision               0.12.0               py38_cu102    pytorch
tornado                   6.1              py38h27cfd23_0  
tqdm                      4.64.0                   pypi_0    pypi
trimesh                   3.11.2                   pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0  
urllib3                   1.26.9           py38h06a4308_0  
wandb                     0.12.15                  pypi_0    pypi
werkzeug                  2.1.1                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
x264                      1!161.3030           h7f98852_1    conda-forge
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.7.2                    pypi_0    pypi
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.0                ha4553b6_1

**Comment by cats0212** [comment]
Annotated code line 41 and 44 of surface_samples_remesh_visible.py.
line 41 `#area_reduction = trimesh.load_mesh(remesh_fp).area / trimesh.load_mesh(mesh_fp).area`

But I run `python -m surfemb.scripts.misc.surface_samples_sample_even`
another problem:
Traceback (most recent call last):
  File "/home/c/surfemb/surfemb/scripts/misc/surface_samples_sample_even.py", line 28, in <module>
    ms.load_new_mesh(str(mesh_fp.absolute()))
pymeshlab.pmeshlab.PyMeshLabException: Unable to open file: /home/c/surfemb/data/remesh_visible/ycbv/obj_000013.ply
Error encountered while loading file:
"/home/c/surfemb/data/remesh_visible/ycbv/obj_000013.ply"

Error details: Bad vertex index in face


# packages in environment
trimesh                   3.10.8 
pymeshlab            0.2.1

**Comment by hengseuer** [comment]
https://github.com/rasmushaugaard/surfemb/blob/53e1852433a3b2b84fedc7a3a01674fe1b6189cc/surfemb/scripts/misc/surface_samples_remesh_visible.py#L39
`ms.save_current_mesh(str(remesh_fp.absolute()), save_textures=False, binary=False)`
