### ISSUE TITLE
Some problems encountered when training tless

### ISSUE THREAD

**Issue by transcend-lzy** [rasmushaugaard/surfemb#12]
I downloaded the tless on bop and put it under data/bop/tless, the code can load the cad models , i use python -m surfemb.scripts.train tless --gpus 0 to run, but it runs to After trainer.fit, the following error will occur：
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'trimesh.caching.TrackedArray'>
Sorry, am I setting it wrong?
![image](https://user-images.githubusercontent.com/60084969/167443146-38bbc1f3-ce2d-4011-a61c-68f6344a3c8d.png)

**Comment by transcend-lzy** [comment]
There should be a problem with the instance obtained by the dataset, but I have not changed the code, I hope to get your help, thank you

**Comment by cp1108** [comment]
It maybe environment problems.I had encountered this problem.`conda env create -f environment.yml` maybe fix it.I forget how I solved this problem

**Comment by transcend-lzy** [comment]
> It maybe environment problems.I had encountered this problem.`conda env create -f environment.yml` maybe fix it.I forget how I solved this problem

Thank, you! I have used conda env create -f environment.yml .  Maybe some auto-installed version is incorrect? Can you show me the difference between our environments? It is mine
![image](https://user-images.githubusercontent.com/60084969/167521886-edef2aa1-d43e-4051-83f2-22aef967321e.png)

**Comment by hengseuer** [comment]
https://github.com/rasmushaugaard/surfemb/blob/53e1852433a3b2b84fedc7a3a01674fe1b6189cc/surfemb/data/pose_auxs.py#L57
`inst['surface_samples'] = np.array(mesh.sample(self.n_samples)).astype(np.float32) `

**Comment by LeroyChou** [comment]
> https://github.com/rasmushaugaard/surfemb/blob/53e1852433a3b2b84fedc7a3a01674fe1b6189cc/surfemb/data/pose_auxs.py#L57
> 
> 
> `inst['surface_samples'] = np.array(mesh.sample(self.n_samples)).astype(np.float32) `

Wow, This works! Thank you.

**Comment by transcend-lzy** [comment]
> np.array(mesh.sample(self.n_samples)).astype(np.float32)
Thank you!

**Comment by transcend-lzy** [comment]
> https://github.com/rasmushaugaard/surfemb/blob/53e1852433a3b2b84fedc7a3a01674fe1b6189cc/surfemb/data/pose_auxs.py#L57
> 
> 
> `inst['surface_samples'] = np.array(mesh.sample(self.n_samples)).astype(np.float32) `

Thank you!

**Comment by domef** [comment]
Why is this fix not commited on master branch?
