### ISSUE TITLE
About the instantiation of renderer

### ISSUE THREAD

**Issue by Whishing** [rasmushaugaard/surfemb#14]
I'm trying to use your render code for depth image generation.  Although I have set 'OPENLAS_NUM_THREADS'  etc,  segmentation fault encounter in work always occurs if num_worker>0,  do you have any idea about this?

**Comment by rasmushaugaard** [comment]
It's not something I've encountered. 
Do you have a minimal reproducible example?

**Comment by Whishing** [comment]
> It's not something I've encountered. Do you have a minimal reproducible example?

It's becasue I have instanced the renderer before the instantiation in the worker to calculate some parameters, but I don't know why.  Make renderer None before initialize the dataloader also does not work.
