### ISSUE TITLE
About the implementation of Unet.

### ISSUE THREAD

**Issue by LeroyChou** [rasmushaugaard/surfemb#16]
Hi, thank you for your great work!
I notice that your implementation of Unet is a little different from the original one. in [this line](https://github.com/rasmushaugaard/surfemb/blob/53e1852433a3b2b84fedc7a3a01674fe1b6189cc/surfemb/dep/unet.py#L76) you feed the data from "contracting path" into a `convrelu`  before catenating it with current data from "expansive path", which you do in the next line. But the author of Unet merely copy it, with no furthur process. So what's the reason you do in such manner?

**Comment by rasmushaugaard** [comment]
Hi, thanks!
The Unet implementation is based on [this one](https://github.com/usuyama/pytorch-unet) (stated in the top of the file).
Adding these 1x1 convolutions is not our contribution.

**Comment by LeroyChou** [comment]
I got it. Thank you!
