### ISSUE TITLE
train on a custom dataset

### ISSUE THREAD

**Issue by LeroyChou** [rasmushaugaard/surfemb#18]
I'm trying to train `surfemb` on a custom dataset. But when I do inference, I find some files/dirs are musts(they're  `detection_results`, `surface_samples`, `surface_samples_normals`). 
For `dectection_results`, I've already known it's from `CosyPose`,  but I don't know how to generate it in detail.
For `surface_samples`, I followed your guidance that  run command `$ python -m surfemb.scripts.misc.surface_samples_remesh_visible clip` first. But I encountered this error:
```bash
Traceback (most recent call last):
  File "/root/miniconda3/envs/surfemb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/surfemb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/surfemb/surfemb/scripts/misc/surface_samples_remesh_visible.py", line 32, in <module>
    ms.compute_scalar_ambient_occlusion(occmode='per-Face (deprecated)', reqviews=256)
AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'compute_scalar_ambient_occlusion'
```
Could you please give me any suggestions on these two problems?

**Comment by LeroyChou** [comment]
The second problem has been addressed. coverting pymeshlab to version 0.2 works.

**Comment by rasmushaugaard** [comment]
Hi

Perhaps you can get some inspiration from the script that loads the cosypose detections and saves them, [here](https://github.com/rasmushaugaard/surfemb/blob/master/surfemb/scripts/misc/load_detection_results.py).

BR Rasmus

**Comment by LeroyChou** [comment]
Thank you. I've been studying cosypose's codes these day, and your suggestions help me a lot.

**Comment by smoothumut** [comment]
> The second problem has been addressed. coverting pymeshlab to version 0.2 works.

Hi LeroyChou , I am having similar problem with pymeshlab

After changing pymeshlab version to 0.2 , how did you change these 3 lines in suface_samples_remesh_visible.py in misc folder. Because in that version, some functions are renamed or changed. so pymeshlab says it has no attribute ...

    ms.repair_non_manifold_edges_by_removing_faces()
    ms.subdivision_surfaces_midpoint(iterations=10, threshold=pymeshlab.Percentage(args.remesh_percentage))
    ms.ambient_occlusion(occmode='per-Face (deprecated)', reqviews=256)

thanks in advance

**Comment by smoothumut** [comment]
> The second problem has been addressed. coverting pymeshlab to version 0.2 works.

Hi LeroyChou,  I am having problem with 

ms.ambient_occlusion(occmode='per-Face (deprecated)', reqview=256) 

this line stops the code without giving any error. Did you have the same problem? if so, how did you solve it?
thanks in advance

**Comment by LeroyChou** [comment]
> > The second problem has been addressed. coverting pymeshlab to version 0.2 works.
> 
> Hi LeroyChou, I am having problem with
> 
> ms.ambient_occlusion(occmode='per-Face (deprecated)', reqview=256)
> 
> this line stops the code without giving any error. Did you have the same problem? if so, how did you solve it? thanks in advance

hello.
yes I was troubled by the same problem. My solution is converting the pymeshlab's version to 0.2 and it works in my case.
