### ISSUE TITLE
question about bbox and mask

### ISSUE THREAD

**Issue by smoothumut** [rasmushaugaard/surfemb#22]
Thanks again for this great work. I am still trying to make it work for our case. In order to run the model with our custom dataset, should we need to have bbox and mask in our bop formatted custom dataset? we can provide bbox_visible but not bbox. and we can provide mask_visible but not mask? how important are they? would be bbox_visible and mask_visible enough?
if we need them for this model, do you have any idea how to generate that ?
thanks thanks in advance

**Comment by rasmushaugaard** [comment]
The full mask is found by rendering the object in the ground truth pose during training.
You don't need to provide bbox and mask, but you would probably need to remove the "bbox_obj" from surfemb/data/instance.py.

**Comment by smoothumut** [comment]
thanks a lot for the answer. Deeply appreciated
