### ISSUE TITLE
assert len(obj_ids) > 0 AssertionError

### ISSUE THREAD

**Issue by meropis** [rasmushaugaard/surfemb#25]
PLEASE SEE COMMENT BELOW FOR NEW ERROR:

I'm getting this strange error when I run `python -m surfemb.scripts.infer <path>/data/models/ycbv-jwpvdij1.compact.ckpt --device cuda:0`.

It originates from line 50 of `infer.py`, and also occurs when you run `infer_debug.py`.
If the full error stack would be useful, let me know. 

Full Stack:
`Traceback (most recent call last):
  File "/home/usr/anaconda3/envs/surfemb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/usr/anaconda3/envs/surfemb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/usr/Documents/6DPose/surfemb/scripts/infer.py", line 50, in <module>
    assert len(obj_ids) > 0
AssertionError`

the solution was to rename `ycbv_models` to `ycbv`

**Comment by 3Proto** [comment]
Looking into `infer.py`, I can see that the program is looking for a `ycbv` folder in `/data/bop`

```py
# load data
root = Path('data/bop') / dataset
print(str(root)) #prints "data/bop/ycbv" - which doesn't exist (I only have ycbv_models, ycbv_base and ycbv_test_19)
cfg = config[dataset]
objs, obj_ids = load_objs(root / cfg.model_folder)
```

Is Path('data/bop') working as intended?

**Comment by yangkaihang1998** [comment]
> 

hello,i also meet this promblem,i want to know what`s mean  about ycbv_models to ycbv,could you tell me how to modify this thanks
