### ISSUE TITLE
How do you create the `depth`, `mask` and `mask_visib` from the `rgb` image?

### ISSUE THREAD

**Issue by meropis** [rasmushaugaard/surfemb#27]
I have an rgb image I wish to try and run the program on, with an image I found off the internet (it should work since the image I found contains one of the items the algorithm was trained on). How would I go about creating the `mask_visib`, `mask` and `depth` images from my rgb image?

**Comment by rasmushaugaard** [comment]
You actually don't need any of those. You do need a crop though. 
Perhaps the inference script can help you out.
