### ISSUE TITLE
What does the `current_pose` array values mean?

### ISSUE THREAD

**Issue by meropis** [rasmushaugaard/surfemb#29]
I have modified the `infer_debug` file so that when a pose estimate is completed it sends pose details of the `current_pose` array. My question is what these numbers actually mean? I would assume `x`, `y`, `z`, `pitch`, `roll` and `yaw` but I have no idea which corresponds to which.
![image](https://user-images.githubusercontent.com/64602574/182111323-c44a6eb4-1713-4dba-870a-16ba18ab9912.png)

**Comment by lxwkobe24** [comment]
> I have modified the `infer_debug` file so that when a pose estimate is completed it sends pose details of the `current_pose` array. My question is what these numbers actually mean? I would assume `x`, `y`, `z`, `pitch`, `roll` and `yaw` but I have no idea which corresponds to which. ![image](https://user-images.githubusercontent.com/64602574/182111323-c44a6eb4-1713-4dba-870a-16ba18ab9912.png)

hello,could you tell me how to train 2d detector,thank you so much

**Comment by meropis** [comment]
> 

Dont just comment on random people's issues when you cant get a reply. Try it yourself until someone is generous enough to help you.

**Comment by yangkaihang1998** [comment]
> > 
> 
> Dont just comment on random people's issues when you cant get a reply. Try it yourself until someone is generous enough to help you.

I am sorry for this,hope you could forgive me

**Comment by rasmushaugaard** [comment]
The pose format is rotation matrix and translation: (R, t)

**Comment by yangkaihang1998** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
