### ISSUE TITLE
A question about ambiguities

### ISSUE THREAD

**Issue by pyni** [rasmushaugaard/surfemb#35]
Hi.
Thanks for your work.
I have a question about your paper.
According to your paper, 'uniformly sampled object points are fed through the same key model to provide negative keys'.
But according to InfoNCE loss, the denominator should be query point and negative point. So if the sampled points include the symmetrical points of query point, it will not satisfied the requirement of InfoNCE loss, right?

**Comment by rasmushaugaard** [comment]
Hi, and thanks for your interest.
It is not a requirement of the InfoNCE loss that the negative samples can't include points that are visually similar or even equal to the true point.

**Comment by pyni** [comment]
OK. Thanks.
