### ISSUE TITLE
Any Plan to upgrade?

### ISSUE THREAD

**Issue by smoothumut** [rasmushaugaard/surfemb#36]
Hi Rasmus, 
Your deep learning model is really powerful. There is soo much work in it. I have made it work and using it. For my custom pbr dataset, it works really good, but not perfect.  My question is if you have plans to improve the model to v2? It would be great if you have so
Thanks in advance
Best Regards

**Comment by rasmushaugaard** [comment]
Hi there,
We have extended SurfEmb to multi-view in [EpiSurfEmb](https://arxiv.org/pdf/2210.00924.pdf), but we don't have further plans to extend or revise SurfEmb. 
One of the limitations of SurfEmb and other point-estimate methods is lacking uncertainty quantification. We have recently proposed [SpyroPose](https://arxiv.org/pdf/2303.05308.pdf) which estimates pose distributions.
BR Rasmus

**Comment by smoothumut** [comment]
Hi Rasmus,

Wow, you are definetely doing a great job! I really admire all that work

Regarding EpiSurfEmb, Actually It is what I was looking for : ))

For our case, I am using surfemb and cosypose's multiview algorithm together to make the errors minimize and get a 3d reconstruction. It works good, but when surfemb couldnt get right poses, multiview algorithm makes the results worse as you described in your article.
Your deep learning model is really deep to me : ) but if I understand correctly, It sounds to me that EpiSurfEmb will solve this issue by refining each pose comparing each others deep properties using epipolar geometry, instead of using just their scores and positions in each view.
If it is so, it is very exiting to me. I hope you will share the code soon : )  I will be looking forward to it.

By the way I was also suprised how ground truth 2D detections changes the Pose prediction. Surfemb only use bbox of the 2D detections, not masks, Am I right? I didnt know bboxes are that important.

Thanks thanks in advance and your great work
Umut

**Comment by rasmushaugaard** [comment]
Code for EpiSurfEmb will be released soon. Surfemb predicts the mask, so no mask is needed from the detector.

**Comment by smoothumut** [comment]
Hi Rasmus, is there any update on EpiSurfEmb?

**Comment by rasmushaugaard** [comment]
Hi Umut. I've sent you a mail with a link to the code and a trained tless model.

**Comment by smoothumut** [comment]
Hi Rasmus, I can't say enough about how much appreciated and grateful I have felt with your message : ) 
Thanks a lot for your great works

**Comment by khanh0812** [comment]
@rasmushaugaard , could you send me the released source code for EpiSurfEmb? Many thanks

**Comment by rasmushaugaard** [comment]
> @rasmushaugaard , could you send me the released source code for EpiSurfEmb? Many thanks

Certainly. Do you have a mail i can send it to?

**Comment by khanh0812** [comment]
@rasmushaugaard my email is khanhdb@hcmute.edu.vn, many thanks for your quick response
